---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:     
      - CreateNamespace=true
  source:
    chart: base
    repoURL: https://tis.tetrate.io/charts
    targetRevision: 1.25.3-tetrate3
    helm:
      valuesObject:
        defaultRevision: 1-25-3
        global:
          tag: 1.25.3-tetrate3
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  dependsOn:
    - kind: Application
      name: istio-base
      namespace: argocd