apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shamusx/crispy-octo-couscous.git
    targetRevision: HEAD
    path: apps/bookinfo
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true