apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shamusx/istio-multicluster-demo.git
    path: helm/applications
    targetRevision: main
    helm:
      valueFiles: 
        - https://raw.githubusercontent.com/shamusx/istio-multicluster-demo/refs/heads/main/clusters/cluster1/values/istio.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
      managedFieldsManagers:
        - argocd-server