apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/istio-multicluster.git
    targetRevision: HEAD
    path: clusters/cluster1/infra
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true